name: Docker Image CI

on:
  push:
    branches: [ "main" ]
 # pull_request:
 #   branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: dekoeky/counter:latest
        platforms: |
          linux/amd64
          linux/arm64
          linux/arm32v7
          linux/arm32v6
          linux/arm64v8
          linux/i386
          linux/ppc64le
          linux/riscv64
          linux/s390x
        
