name: Docker Image CI

on:
  push:
    branches: [ "main" ]
 # pull_request:
 #   branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
      with:
        # Needed for GitVersion:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.2.1
      with:
        versionSpec: '6.3.x'

    - name: Run GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v3.2.1


    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: |
          dekoeky/counter:${{ steps.gitversion.outputs.majorMinorPatch }}
          dekoeky/counter:latest
        platforms: |
            linux/amd64
            linux/arm/v6
            linux/arm/v7
            linux/arm64/v8
            linux/386
            linux/ppc64le
            linux/riscv64
            linux/s390x
    
    # This step copies the local README.md to the Docker Hub General Page
    - name: Docker Hub Description
      #https://github.com/peter-evans/dockerhub-description
      uses: peter-evans/dockerhub-description@v4 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: dekoeky/counter
        short-description: ${{ github.event.repository.description }}
        readme-filepath: ./README.md

        
